### ISSUE TITLE
Why remap H and L?

### ISSUE THREAD

**Issue by sushengloong** [neo/vim-config#52]
H and L are for jumping to the top and bottom of the screen. Can someone shed some light on why we should remap them to $ and ^?

https://github.com/neo/vim-config/blob/master/.vim/common_config/key_mappings.vim#L57
```
" jump to far right or left of line
map L $
map H ^
```

**Comment by bakis2011** [comment]
Done with https://github.com/neo/vim-config/pull/54/files
